version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: taxonomy_sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxonomy
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    command: --schema=public
    volumes:
      - sql:/var/lib/mysql/data/
volumes:
  sql: